// auth modal
export const FORGET_PASSWORD_MODAL = 'FORGET_PASSWORD_MODAL';
export const SHOW_OTP_MODAL = 'SHOW_OTP_MODAL';
export const RESET_PASSWORD_MODAL = 'RESET_PASSWORD_MODAL';
export const CREATE_NEW_TEAM_MODAL = 'CREATE_NEW_TEAM_MODAL';
export const INVITE_TO_TEAM_MODAL = 'INVITE_TO_TEAM_MODAL';
export const RENAME_TEAM_MODAL = 'RENAME_TEAM_MODAL';
export const DELETE_TEAM_MODAL = 'DELETE_TEAM_MODAL';
export const UPLOAD_THUMBNAIL_MODAL = 'UPLOAD_THUMBNAIL_MODAL';
export const CHOOSE_TEAM_PLAN_MODAL = 'CHOOSE_TEAM_PLAN_MODAL';
export const ASSET_NAME_MODAL = 'ASSET_NAME_MODAL';
export const MESSAGE_MODAL = 'MESSAGE_MODAL';
export const PUBLISH_EXPERIENCE_MODAL = 'PUBLISH_EXPERIENCE_MODAL';
export const  CANCEL_REVIEW_MODAL = "CANCEL_REVIEW_MODAL"